language: bash
matrix:
    include:
        - os: linux
        - os: windows
        - os: osx 
    allow_failures:
        - os: windows
        - os: osx
script: cp .env.sample .env && make tests